name: Deploymen Project
on: [push, workflow_dispatch]
jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v5
      - name: Install Node JS
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Install dependecies
        run: npm ci
      - name: Run Tests
        run: npm test
  deploy:
    needs: [teste]
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v5
      - name: Install Node JS
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Install dependecies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Deploy
        run: echo "Deploying..."